RDCC-3782: Collating Dependabot PRs
hmcts/rd-professional-api pull request #1144
Opened 2021-12-17 16:10 UTC by AdilOoze

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-12-20 13:40 UTC, SujeethKumarAri requested changes
Approved but blocking to avoid accidental merge

2022-01-04 11:29 UTC, SujeethKumarAri submitted a review, later dismissed

2022-01-04 11:29 UTC, sahitya-desireddy submitted a review, later dismissed

2022-01-04 11:39 UTC, souravroy2021 approved these changes

2022-01-05 14:02 UTC, sahitya-desireddy approved these changes

2022-01-05 14:08 UTC, SujeethKumarAri approved these changes

2022-01-05 15:02 UTC, merged