PRD - Handle Verbose Error Messages
hmcts/rd-professional-api pull request #1196
Opened 2022-03-23 15:11 UTC by sahitya-desireddy

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-4253

### Change description ###
PRD - Handle Verbose Error Messages

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-03-24 11:14 UTC, AdilOoze approved these changes

2022-03-24 11:54 UTC, SujeethKumarAri requested changes
I would say,  if `HttpMessageNotReadableException` has already being handled then no need to make any changes. It would be a surprise for the consumers if we return different error message now
@shreedhar-hmcts @kavithagade12 - your thoughts?

2022-03-25 09:18 UTC, SujeethKumarAri commented
I think you can close this PR @sahitya-desireddy

2022-03-25 09:31 UTC, sahitya-desireddy commented
closing this PR ... as per team decision this changes are no more required ...

2022-03-25 09:31 UTC, closed without merging