Feat:To handle 500 HTTP responses
hmcts/rd-professional-api pull request #1235
Opened 2022-05-26 11:23 UTC by shivajihmcts

### JIRA link  ###

https://tools.hmcts.net/jira/browse/RDCC-4680

### Change description ###

To handle 500 HTTP responses

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-05-27 08:05 UTC, SujeethKumarAri requested changes

2022-05-27 08:05 UTC, SujeethKumarAri commented on src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/SecurityEndpointFilter.java
> +    public static final String SERVICE_AUTHORIZATION2 = "ServiceAuthorization";
You can remove these unused static variables

2022-06-07 12:45 UTC, arshinsalim approved these changes

2022-06-07 12:54 UTC, nayeemshaik-hmcts approved these changes

2022-06-07 12:58 UTC, SujeethKumarAri approved these changes

2022-06-07 12:59 UTC, merged