RDCC-5592:rd-professional-api code smell issues fixes
hmcts/rd-professional-api pull request #1328
Opened 2022-10-19 09:03 UTC by manukundloo-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-5592

### Change description ###
RDCC-5592:rd-professional-api code smell issues fixes

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-10-19 10:02 UTC, SujeethKumarAri requested changes
Can you please try the below code to fix the Null pointer https://sonarcloud.io/project/issues?resolved=false&id=RDPROFESSIONALAPI&open=AYOnuhWFlhfWzlv2_r6v

`if (infoList.isEmpty() || infoList.get().isEmpty()) {
            throw new InvalidRequest("Request is empty");
        }`
        
    Same for other null pointer exception as well

2022-10-19 12:02 UTC, manukundloo-hmcts commented
Thanks Sujeet for the comment, i have done the changes and pushed the code

2022-10-19 13:16 UTC, SujeethKumarAri approved these changes

2022-10-19 13:38 UTC, rajkatla-hmcts approved these changes

2022-10-19 16:26 UTC, manukundloo-hmcts commented
Thanks Sujeeth for you suggestion. I have accommodated the changes as you requested. We are performing null check as you suggested for list another place we are doing null check for the object so followed legacy null check technique. Please let me know if any change required.

2022-10-20 13:01 UTC, SujeethKumarAri approved these changes

2022-10-20 13:03 UTC, rajkatla-hmcts approved these changes

2022-10-20 13:52 UTC, sahitya-desireddy approved these changes

2022-10-20 14:29 UTC, merged