GA-43: initial proofs
hmcts/rd-professional-api pull request #1533
Opened 2023-12-15 15:17 UTC by sanjayparekh-hmcts

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/GA-43

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-01-08 10:31 UTC, abul-syed requested changes

2024-01-08 10:31 UTC, abul-syed commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
> +        assertThat(orgResponse.get("http_status").toString().contains("OK"));
```suggestion
        assertThat(orgResponse.get("http_status").toString()).contains("OK");
```

2024-01-08 10:31 UTC, abul-syed commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
> +        assertThat(orgResponse.get("http_status").toString().contains("200"));
```suggestion
        assertThat(orgResponse.get("http_status").toString()).contains("200");
```

2024-01-08 10:31 UTC, abul-syed commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
> +                someMinimalOrganisationRequest().status("ACTIVE").sraId(randomAlphabetic(10)).build());
```suggestion
```

unused

2024-01-08 10:31 UTC, abul-syed commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
> +        assertThat(orgResponse.get("http_status").toString().contains("OK"));
with current format of brackets even something like

`assertThat(orgResponse.get("http_status").toString().contains("123"));` - passes

2024-01-08 10:31 UTC, abul-syed commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
> +        String orgIdentifier3 = createOrganisationWithGivenRequest(
there is a `ACTIVE` constant in `AuthorizationEnabledIntegrationTest` - which can be used

2024-01-08 13:14 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
> +    }
done

2024-01-08 13:39 UTC, abul-syed commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
> +        String orgIdentifier3 = createOrganisationWithGivenRequest(
makes sense

2024-01-10 11:02 UTC, abul-syed approved these changes

2024-01-11 11:59 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
> +                                                                    String status, Integer page, Integer size) {
I think thats a good suggestion - will do that

2024-01-11 11:59 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
> +        LocalDateTime formattedSince = null;
I saw that, but the orther parms in this code stack have also NOT used optional, so thats why I stuck with their approach

2024-01-16 09:59 UTC, abul-syed submitted a review, later dismissed
LGTM

2024-01-18 16:07 UTC, rajkatla-hmcts requested changes

2024-01-18 16:07 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
> +        assertThat(orgResponse3Size).isEqualTo(3);
check response has these 2 new fields along with existing response fields:
lastUpdated, organisationProfileIds

2024-01-18 16:07 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
> +        assertThat(orgResponse.get("http_status").toString()).contains("OK");
same as above comment, check response has these 2 new fields along with existing response fields:
lastUpdated, organisationProfileIds

2024-01-18 16:07 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
> +        assertThat(organisationActive.get("name")).isEqualTo("some-org-name-after");
same as above , check response has these 2 new fields along with existing response fields:
lastUpdated, organisationProfileIds

2024-01-19 12:02 UTC, sanjayparekh-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
> +        assertThat(organisationActive.get("name")).isEqualTo("some-org-name-after");
added

2024-01-19 12:03 UTC, sanjayparekh-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
> +        assertThat(orgResponse3Size).isEqualTo(3);
added

2024-01-19 12:03 UTC, sanjayparekh-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
> +        assertThat(orgResponse.get("http_status").toString()).contains("OK");
added

2024-01-22 13:39 UTC, rajkatla-hmcts submitted a review, later dismissed

2024-02-05 18:39 UTC, rajkatla-hmcts submitted a review, later dismissed

2024-02-06 11:06 UTC, abul-syed submitted a review, later dismissed

2024-02-06 12:17 UTC, helenbirdhmcts requested changes
swap variable since for lastUpdatedSince in all places where since has been used

2024-02-06 12:17 UTC, helenbirdhmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
> +    static final String SINCE_TIMESTAMP_FORMAT = "yyyy-MM-dd'T'HH:mm:ss";
as with the other PR, perhaps since should be last updated since instead, so its obvious what its for

2024-02-19 21:41 UTC, rajkatla-hmcts approved these changes

2024-02-21 14:57 UTC, kiran-yenigala-hmcts approved these changes

2024-02-21 15:08 UTC, bkpatel81 approved these changes

2024-02-22 09:21 UTC, abul-syed approved these changes

2024-02-22 13:51 UTC, merged