DTSRD-2138.Delete DX address for an organisation
hmcts/rd-professional-api pull request #1559
Opened 2024-02-09 09:49 UTC by SabinaHMCTS

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-05-09 11:17 UTC, SabinaHMCTS commented on src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java
>      }
this is not a test .. need @Test above the method also run the test and make it pass add assert statements .check that the test covers all functionality by run with code coverage

2024-05-09 11:18 UTC, SabinaHMCTS commented on src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java
> +
add negative tests to cover exceptions from eg empty contact lists empty dx addresses etc

2024-06-10 15:41 UTC, rajkatla-hmcts requested changes

2024-06-10 15:41 UTC, rajkatla-hmcts commented on src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java
> +    public void deleteEmptyDxAddressShouldReturnError() {
as discussed, rename this method to deleteNonExistDxAddressShouldReturnError

2024-06-10 15:42 UTC, rajkatla-hmcts requested changes

2024-06-10 15:42 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/DeleteDxAddressTest.java
> +    }
Please these 2 tests in IT test
1) add empty contact information list error scenario
2) non exist dx address error scenario

2024-07-01 11:44 UTC, rajkatla-hmcts requested changes

2024-07-01 11:44 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/DeleteDxAddressTest.java
> +        assertThat(deleteResponse.get("http_status")).isEqualTo(400);
api return status code 404 when dx address is not found

2024-09-10 14:57 UTC, rajkatla-hmcts requested changes

2024-09-10 14:57 UTC, rajkatla-hmcts commented on src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
> +        @Valid @NotNull @RequestBody DxAddressCreationRequest dxAddressRequest,
The DxAddressCreationRequest class has both dxNumber and dxExchange properties as mandatory. However, for deleting an dx address, only dxNumber is used. Can you rename Request to a more generic name, like DxAddressRequest, as the current name is confusing for delete operations? Additionally, please remove the @NotNull annotation on the dxExchange property. For the old logic, manually handle the null check for the dxExchange field and return an error where necessary.

2026-05-14 19:37 UTC, closed without merging