DTSRD-2134.Delete User from Professional
hmcts/rd-professional-api pull request #1589
Opened 2024-04-23 14:59 UTC by SabinaHMCTS

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-04-29 16:13 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
> +        if (emails.isEmpty()) {
minor: checking for emails could be first, even before creation of response object

2024-04-29 16:52 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
> +                        professionalUserRepository.delete(professionalUser);
lines 839 and 840:
waiting on IO inside a stream will block all other requests from all other spring-boot threads (all streams in JVM use a separate thread pool called CFJP - CommonForkJoinPool), both calls should be moved outside stream processing into a CompletableFuture call or else for-each loop.

2024-04-29 16:55 UTC, lukasz-wolski requested changes
Please refer to inlined comments

2024-05-20 09:28 UTC, rajkatla-hmcts requested changes

2024-05-20 09:28 UTC, rajkatla-hmcts commented on src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
> +                Set<String> userIds = new HashSet<>();
you dont need this set object, return it from stream itself

2024-05-20 09:28 UTC, rajkatla-hmcts commented on src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
> +                        userIds.add(professionalUser.getUserIdentifier());
dont need this, return ids from stream map and collect as set

2024-05-20 09:28 UTC, rajkatla-hmcts commented on src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
> +                return userIds.stream().iterator().next();
dont need this line

2024-05-20 09:28 UTC, rajkatla-hmcts commented on src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
> +            new DeleteUserProfilesRequest(userIdsToBeDeleted.stream().collect(
its already set object why it has to convert to set again ?

2024-05-20 09:28 UTC, rajkatla-hmcts commented on src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
> +            .deleteUserProfilesFromUp(deleteUserProfileRequest, userProfileFeignClient);
have you thought about tracking deletion failed email addresses and return error message with failed email ids ?

2024-05-20 09:28 UTC, rajkatla-hmcts commented on src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
> +        if (deleteOrganisationResponse == null) {
this line is not required, response will contain either success or error status or it wont come back if any FeignException

2024-05-20 09:28 UTC, rajkatla-hmcts commented on src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalControllerTest.java
> +            new DeleteUserResponse(STATUS_CODE_204, "The organisation has deleted successfully");
wrong message you are trying delete user : The organisation has deleted successfully

2024-05-20 09:28 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/DeleteUserIntegrationTest.java
> +
1)Add scenario for deletion failed email addresses from PRD
2)Add scenario for deletion failed email addresses from UP

2024-05-20 09:28 UTC, rajkatla-hmcts commented on src/main/java/uk/gov/hmcts/reform/professionalapi/repository/UserAttributeRepository.java
> +    @Query(value = "delete from dbrefdata.user_attribute ua where ua.professional_user_id=:profUserId",
do you need this native query, cascade delete should take care of it

2024-05-20 09:28 UTC, rajkatla-hmcts commented on src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
> +            new DeleteUserResponse(204, "The organisation has deleted successfully");
wrong message you are trying delete user : The organisation has deleted successfully

2026-05-14 19:37 UTC, closed without merging