Fix db migration issues
hmcts/rd-professional-api pull request #1609
Opened 2024-05-17 10:09 UTC by kiran-yenigala-hmcts

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-05-17 10:10 UTC, SabinaHMCTS approved these changes

2024-05-17 10:13 UTC, lukasz-wolski submitted a review, later dismissed

2024-05-17 10:42 UTC, SabinaHMCTS approved these changes

2024-05-17 10:44 UTC, lukasz-wolski submitted a review, later dismissed

2024-05-17 11:09 UTC, lukasz-wolski requested changes
proposing to use flyway 9.22.3 please see inlined comment

2024-05-20 11:30 UTC, SabinaHMCTS approved these changes

2024-05-20 11:37 UTC, kiran-yenigala-hmcts commented on build.gradle
> +    id "org.flywaydb.flyway" version '10.13.0'
fixed the checkstyle issues

2024-05-20 13:04 UTC, merged